// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::todo,
    clippy::needless_pass_by_value,
    clippy::needless_pass_by_ref_mut,
    clippy::ptr_arg,
    clippy::boxed_local,
)]

#[path = "2_take_ownership.rs"]
mod _2_take_ownership;
#[path = "3_borrow_string.rs"]
mod _3_borrow_string;
#[path = "4_mutate_string.rs"]
mod _4_mutate_string;
#[path = "5_experiments.rs"]
mod _5_experiments;

fn main() {}
