// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::todo,
    clippy::needless_pass_by_value,
    clippy::needless_pass_by_ref_mut,
    clippy::ptr_arg,
    clippy::boxed_local,
)]

#[path = "2_parse_line.rs"]
mod _2_parse_line;
#[path = "3_parse_file.rs"]
mod _3_parse_file;
#[path = "4_get_var.rs"]
mod _4_get_var;
#[path = "5_validate.rs"]
mod _5_validate;

fn main() {}
