//! Generate aggregator `main.rs` files for multi-step chapters.
//!
//! See `docs/multi_step_chapters_plan.md`. A chapter is "multi-step" if it
//! contains any sibling `<n>_<slug>.rs` files. For those chapters we
//! emit a `main.rs` that wires every step file in as a module:
//!
//! ```ignore
//! // @generated by build.rs - do not edit
//! #![allow(dead_code, unused_imports)]
//! mod _2_unwrap;
//! mod _4_combinators;
//! fn main() {}
//! ```
//!
//! Cargo's example resolution then sees one binary per chapter
//! (`cargo test --example 07_option`) but a single `cargo test` filter
//! like `_2_unwrap::` runs just that step's tests.
//!
//! Single-step (legacy) chapters \u2014 directories that contain only a
//! hand-written `main.rs` and no sibling `.rs` files \u2014 are left
//! completely alone so this script is safe to run against the existing
//! tree.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

const GENERATED_HEADER: &str = "// @generated by build.rs - do not edit by hand.\n// This file aggregates the chapter's step files (`<n>_<slug>.rs`).\n// To change it, edit (or add/remove) those step files and re-run `cargo build`.\n";

fn main() {
    println!("cargo:rerun-if-changed=examples");
    println!("cargo:rerun-if-changed=build.rs");

    emit_git_build_info();

    let examples = Path::new("examples");
    if !examples.exists() {
        return;
    }

    let chapter_dirs = match fs::read_dir(examples) {
        Ok(rd) => rd,
        Err(e) => {
            println!("cargo:warning=build.rs: cannot read examples/: {e}");
            return;
        }
    };

    for entry in chapter_dirs.flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        // Tell cargo to re-run if anything inside this chapter changes.
        println!("cargo:rerun-if-changed={}", path.display());
        if let Err(e) = process_chapter(&path) {
            println!("cargo:warning=build.rs: skipping {}: {e}", path.display());
        }
    }
}

/// Emit `GIT_BRANCH` / `GIT_HASH` as compile-time env vars for the server footer.
///
/// Best-effort: if `git` isn't on PATH or `.git` isn't present (e.g. a Docker
/// build from a tarball), we emit `unknown` and move on. `cargo:rerun-if-changed`
/// on `.git/HEAD` refreshes the values when the checked-out commit/branch changes.
fn emit_git_build_info() {
    println!("cargo:rerun-if-changed=.git/HEAD");

    let git = |args: &[&str]| -> Option<String> {
        let out = std::process::Command::new("git").args(args).output().ok()?;
        if !out.status.success() {
            return None;
        }
        let s = String::from_utf8_lossy(&out.stdout).trim().to_string();
        if s.is_empty() { None } else { Some(s) }
    };

    let branch = git(&["rev-parse", "--abbrev-ref", "HEAD"]).unwrap_or_else(|| "unknown".into());
    let hash = git(&["rev-parse", "--short", "HEAD"]).unwrap_or_else(|| "unknown".into());
    println!("cargo:rustc-env=GIT_BRANCH={branch}");
    println!("cargo:rustc-env=GIT_HASH={hash}");
}

fn process_chapter(dir: &Path) -> Result<(), String> {
    let step_files = collect_step_files(dir)?;
    if step_files.is_empty() {
        // Legacy single-step chapter. Leave its `main.rs` alone.
        return Ok(());
    }

    let mut body = String::from(GENERATED_HEADER);
    // Stub-friendly allows: every step starts as a `todo!()` skeleton
    // with named parameters the learner will eventually use. Without
    // these allows, clippy floods the example with warnings about the
    // unused parameters and the `todo!()` macro itself, which buries
    // any actual lint a learner might want to see in their own code.
    //
    // `ptr_arg` and `boxed_local` are allowed because the chapters on
    // `Vec`, `String`, and `Box<T>` deliberately use those concrete
    // types in function signatures to teach them; clippy's "prefer a
    // slice" / "take by value" suggestions would defeat the lesson.
    body.push_str(
        "#![allow(\n    \
         dead_code,\n    \
         unused_imports,\n    \
         unused_variables,\n    \
         clippy::todo,\n    \
         clippy::needless_pass_by_value,\n    \
         clippy::needless_pass_by_ref_mut,\n    \
         clippy::ptr_arg,\n    \
         clippy::boxed_local\n\
         )]\n\n",
    );
    for (_n, path, module_name) in &step_files {
        // The on-disk filename starts with a digit (`2_fallback.rs`), so
        // we name the module `_2_fallback` (legal identifier) and point
        // it at the file via `#[path]`. Keeps filenames human-friendly
        // while satisfying Rust's identifier rules.
        let filename = path
            .file_name()
            .and_then(|s| s.to_str())
            .ok_or_else(|| "step file has no filename".to_string())?;
        let _ = writeln!(body, "#[path = \"{filename}\"]");
        let _ = writeln!(body, "mod {module_name};");
    }
    body.push_str("\nfn main() {}\n");

    let main_rs = dir.join("main.rs");
    // Only write when the content actually changed so we don't bust
    // mtimes on every build and trigger needless rebuilds downstream.
    let needs_write = fs::read_to_string(&main_rs).map_or(true, |existing| existing != body);
    if needs_write {
        fs::write(&main_rs, body).map_err(|e| format!("writing {}: {e}", main_rs.display()))?;
    }
    Ok(())
}

/// Discover `<n>_<slug>.rs` step files in a chapter dir, returning
/// `(order, path, module_name)` triples sorted by `order`. The module
/// name has a leading underscore so file names starting with a digit
/// are valid Rust identifiers (`_2_unwrap`).
fn collect_step_files(dir: &Path) -> Result<Vec<(u32, PathBuf, String)>, String> {
    let read = fs::read_dir(dir).map_err(|e| format!("reading {}: {e}", dir.display()))?;
    let mut out: Vec<(u32, PathBuf, String)> = Vec::new();
    for entry in read.flatten() {
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("rs") {
            continue;
        }
        let Some(filename) = path.file_name().and_then(|s| s.to_str()) else {
            continue;
        };
        if filename == "main.rs" {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        let Some((order_str, rest)) = stem.split_once('_') else {
            continue;
        };
        let Ok(order) = order_str.parse::<u32>() else {
            continue;
        };
        // Module name: leading underscore lets us keep the visible number.
        let module_name = format!("_{order}_{rest}");
        if !is_valid_ident(&module_name) {
            return Err(format!(
                "step file `{filename}` produces invalid module name `{module_name}`"
            ));
        }
        out.push((order, path, module_name));
    }
    out.sort_by_key(|(n, _, _)| *n);
    Ok(out)
}

fn is_valid_ident(s: &str) -> bool {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) if c == '_' || c.is_ascii_alphabetic() => {}
        _ => return false,
    }
    chars.all(|c| c == '_' || c.is_ascii_alphanumeric())
}
