// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::todo,
    clippy::needless_pass_by_value,
    clippy::needless_pass_by_ref_mut,
    clippy::ptr_arg,
    clippy::boxed_local
)]

#[path = "3_simple_line.rs"]
mod _3_simple_line;
#[path = "4_quoted_line.rs"]
mod _4_quoted_line;
#[path = "5_parse_file.rs"]
mod _5_parse_file;
#[path = "6_records.rs"]
mod _6_records;

fn main() {}
