// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(dead_code, unused_imports)]

#[path = "3_stray_semicolon.rs"]
mod _3_stray_semicolon;
#[path = "4_countdown.rs"]
mod _4_countdown;
#[path = "5_sum_to.rs"]
mod _5_sum_to;
#[path = "6_cap_at.rs"]
mod _6_cap_at;

fn main() {}
