// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::todo,
    clippy::needless_pass_by_value,
    clippy::needless_pass_by_ref_mut,
    clippy::ptr_arg,
    clippy::boxed_local
)]

#[path = "3_stray_semicolon.rs"]
mod _3_stray_semicolon;
#[path = "4_sum_to.rs"]
mod _4_sum_to;
#[path = "5_cap_at.rs"]
mod _5_cap_at;

fn main() {}
