// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(dead_code, unused_imports)]

#[path = "2_greet.rs"]
mod _2_greet;
#[path = "3_celsius_to_fahrenheit.rs"]
mod _3_celsius_to_fahrenheit;
#[path = "4_min.rs"]
mod _4_min;
#[path = "5_is_even.rs"]
mod _5_is_even;

fn main() {}
