// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(dead_code, unused_imports)]

#[path = "2_stray_semicolon.rs"]
mod _2_stray_semicolon;
#[path = "3_countdown.rs"]
mod _3_countdown;
#[path = "4_sum_to.rs"]
mod _4_sum_to;
#[path = "5_cap_at.rs"]
mod _5_cap_at;

fn main() {}
