// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::todo,
    clippy::needless_pass_by_value,
    clippy::needless_pass_by_ref_mut,
    clippy::ptr_arg,
    clippy::boxed_local
)]

#[path = "3_ferris_mood.rs"]
mod _3_ferris_mood;
#[path = "4_factorial.rs"]
mod _4_factorial;
#[path = "5_count_evens.rs"]
mod _5_count_evens;
#[path = "6_digit_count.rs"]
mod _6_digit_count;

fn main() {}
