// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(dead_code, unused_imports)]

#[path = "3_is_strong.rs"]
mod _3_is_strong;
#[path = "4_char_classes.rs"]
mod _4_char_classes;
#[path = "5_generate.rs"]
mod _5_generate;
#[path = "6_advisor.rs"]
mod _6_advisor;
#[path = "7_validate.rs"]
mod _7_validate;

fn main() {}
