// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::todo,
    clippy::needless_pass_by_value,
    clippy::needless_pass_by_ref_mut,
    clippy::ptr_arg,
    clippy::boxed_local
)]

#[path = "2_add_parsed_numbers.rs"]
mod _2_add_parsed_numbers;
#[path = "3_count_file_lines.rs"]
mod _3_count_file_lines;
#[path = "4_sum_numbers.rs"]
mod _4_sum_numbers;

fn main() {}
