// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(dead_code, unused_imports)]

#[path = "2_add_parsed_numbers.rs"]
mod _2_add_parsed_numbers;
#[path = "3_count_file_lines.rs"]
mod _3_count_file_lines;
#[path = "4_sum_numbers_in_file.rs"]
mod _4_sum_numbers_in_file;

fn main() {}
