// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::todo,
    clippy::needless_pass_by_value,
    clippy::needless_pass_by_ref_mut,
    clippy::ptr_arg,
    clippy::boxed_local
)]

#[path = "2_count_words.rs"]
mod _2_count_words;
#[path = "3_most_common_word.rs"]
mod _3_most_common_word;
#[path = "4_text_stats.rs"]
mod _4_text_stats;

fn main() {}
