// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(dead_code, unused_imports)]

#[path = "2_new.rs"]
mod _2_new;
#[path = "3_display_name.rs"]
mod _3_display_name;
#[path = "4_record_login.rs"]
mod _4_record_login;
#[path = "5_can_access_premium.rs"]
mod _5_can_access_premium;

fn main() {}
