// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(dead_code, unused_imports)]

#[path = "2_calculate.rs"]
mod _2_calculate;
#[path = "3_settings.rs"]
mod _3_settings;
#[path = "4_status.rs"]
mod _4_status;

fn main() {}
