// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(dead_code, unused_imports)]

#[path = "2_create_default_config.rs"]
mod _2_create_default_config;
#[path = "3_set_config_value.rs"]
mod _3_set_config_value;
#[path = "4_get_config_value.rs"]
mod _4_get_config_value;
#[path = "5_count_words.rs"]
mod _5_count_words;

fn main() {}
