// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::todo,
    clippy::needless_pass_by_value,
    clippy::needless_pass_by_ref_mut,
    clippy::ptr_arg,
    clippy::boxed_local
)]

#[path = "3_add_health.rs"]
mod _3_add_health;
#[path = "4_damage_with_bonus.rs"]
mod _4_damage_with_bonus;
#[path = "5_parse_positive_integer.rs"]
mod _5_parse_positive_integer;

fn main() {}
