// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(dead_code, unused_imports)]

#[path = "2_get_user_info.rs"]
mod _2_get_user_info;
#[path = "3_rectangle_measurements.rs"]
mod _3_rectangle_measurements;
#[path = "4_get_first_name.rs"]
mod _4_get_first_name;
#[path = "5_swap_values.rs"]
mod _5_swap_values;

fn main() {}
