// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(dead_code, unused_imports)]

#[path = "2_classify_number.rs"]
mod _2_classify_number;
#[path = "3_factorial.rs"]
mod _3_factorial;
#[path = "4_count_evens.rs"]
mod _4_count_evens;
#[path = "5_digit_count.rs"]
mod _5_digit_count;

fn main() {}
