// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(dead_code, unused_imports)]

#[path = "3_number_to_string.rs"]
mod _3_number_to_string;
#[path = "4_damage_with_crit.rs"]
mod _4_damage_with_crit;
#[path = "5_parse_positive_integer.rs"]
mod _5_parse_positive_integer;

fn main() {}
