// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(dead_code, unused_imports)]

#[path = "2_display_temperature.rs"]
mod _2_display_temperature;
#[path = "3_describable.rs"]
mod _3_describable;
#[path = "4_logger.rs"]
mod _4_logger;
#[path = "5_validate.rs"]
mod _5_validate;

fn main() {}
