// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(dead_code, unused_imports)]

#[path = "2_count_chars.rs"]
mod _2_count_chars;
#[path = "3_shout.rs"]
mod _3_shout;
#[path = "4_has_uppercase.rs"]
mod _4_has_uppercase;

fn main() {}
