// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::todo,
    clippy::needless_pass_by_value,
    clippy::needless_pass_by_ref_mut,
    clippy::ptr_arg,
    clippy::boxed_local
)]

#[path = "02_display_temperature.rs"]
mod _2_display_temperature;
#[path = "03_describable.rs"]
mod _3_describable;
#[path = "04_print_descriptions.rs"]
mod _4_print_descriptions;
#[path = "05_logger.rs"]
mod _5_logger;
#[path = "06_logger_override.rs"]
mod _6_logger_override;
#[path = "07_validation_rules.rs"]
mod _7_validation_rules;
#[path = "08_mixed_shelf.rs"]
mod _8_mixed_shelf;
#[path = "09_collect_errors.rs"]
mod _9_collect_errors;

fn main() {}
