// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::todo,
    clippy::needless_pass_by_value,
    clippy::needless_pass_by_ref_mut,
    clippy::ptr_arg,
    clippy::boxed_local,
)]

#[path = "2_boxed_sum.rs"]
mod _2_boxed_sum;
#[path = "3_expr_tree.rs"]
mod _3_expr_tree;
#[path = "4_pipeline.rs"]
mod _4_pipeline;

fn main() {}
