// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(dead_code, unused_imports)]

#[path = "2_welcome.rs"]
mod _2_welcome;
#[path = "3_count_chars.rs"]
mod _3_count_chars;
#[path = "4_shout.rs"]
mod _4_shout;
#[path = "5_has_uppercase.rs"]
mod _5_has_uppercase;

fn main() {}
