// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::todo,
    clippy::needless_pass_by_value,
    clippy::needless_pass_by_ref_mut,
    clippy::ptr_arg,
    clippy::boxed_local
)]

#[path = "2_add_item.rs"]
mod _2_add_item;
#[path = "3_contains_item.rs"]
mod _3_contains_item;
#[path = "4_create_shopping_list.rs"]
mod _4_create_shopping_list;

fn main() {}
