// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(dead_code, unused_imports)]

#[path = "2_count_words.rs"]
mod _2_count_words;
#[path = "3_most_common_word.rs"]
mod _3_most_common_word;
#[path = "4_frequent_words.rs"]
mod _4_frequent_words;
#[path = "5_text_stats.rs"]
mod _5_text_stats;

fn main() {}
