// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(dead_code, unused_imports)]

#[path = "3_calculate.rs"]
mod _3_calculate;
#[path = "4_status.rs"]
mod _4_status;
#[path = "5_settings.rs"]
mod _5_settings;

fn main() {}
