// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(dead_code, unused_imports)]

#[path = "2_fallback.rs"]
mod _2_fallback;
#[path = "3_transform.rs"]
mod _3_transform;
#[path = "4_first_char.rs"]
mod _4_first_char;
#[path = "5_find_user.rs"]
mod _5_find_user;

fn main() {}
