// @generated by build.rs - do not edit by hand.
// This file aggregates the chapter's step files (`<n>_<slug>.rs`).
// To change it, edit (or add/remove) those step files and re-run `cargo build`.
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::todo,
    clippy::needless_pass_by_value,
    clippy::needless_pass_by_ref_mut,
    clippy::ptr_arg,
    clippy::boxed_local
)]

#[path = "3_sum.rs"]
mod _3_sum;
#[path = "4_map.rs"]
mod _4_map;
#[path = "5_filter.rs"]
mod _5_filter;
#[path = "6_filter_to_string.rs"]
mod _6_filter_to_string;

fn main() {}
